# Generates src/components/Wordmark.tsx: the "BlinkRest" wordmark as vector
# paths traced from the Bricolage Grotesque ExtraBold font.
#
# Paths, not <Text>: iOS kept clipping the last letter of each word when
# drawing this font with tight letter spacing, and a bundled PNG didn't load
# in Expo Go. Vector paths need no font, no image fetch and no text layout.
#
# Usage (needs fontTools and node_modules installed):
#   pip install fonttools && python3 scripts/render-wordmark.py

from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
FONT = ROOT / "node_modules/@expo-google-fonts/bricolage-grotesque/800ExtraBold/BricolageGrotesque_800ExtraBold.ttf"
OUT = ROOT / "src/components/Wordmark.tsx"

WORDS = [("Blink", "#FFFFFF"), ("Rest", "#FF5A36")]
LETTER_SPACING_EM = -1 / 44  # -1px at the 44px size the design uses
PAD_EM = 0.04

font = TTFont(str(FONT))
upm = font["head"].unitsPerEm
cmap = font.getBestCmap()
glyphs = font.getGlyphSet()
hmtx = font["hmtx"]
spacing = LETTER_SPACING_EM * upm

x = 0.0
paths = []
bounds = BoundsPen(glyphs)
for word, color in WORDS:
    pen = SVGPathPen(glyphs)
    for ch in word:
        name = cmap[ord(ch)]
        # Font units are y-up; SVG is y-down.
        transform = (1, 0, 0, -1, x, 0)
        glyphs[name].draw(TransformPen(pen, transform))
        glyphs[name].draw(TransformPen(bounds, transform))
        x += hmtx[name][0] + spacing
    paths.append((pen.getCommands(), color))

xmin, ymin, xmax, ymax = bounds.bounds
pad = PAD_EM * upm
vb = (xmin - pad, ymin - pad, (xmax - xmin) + 2 * pad, (ymax - ymin) + 2 * pad)
aspect = vb[2] / vb[3]

lines = [
    "// Generated by scripts/render-wordmark.py — do not edit by hand.",
    "import Svg, { Path } from 'react-native-svg';",
    "",
    f"const ASPECT = {aspect:.4f};",
    "",
    "export function Wordmark({ height = 43 }: { height?: number }) {",
    "  return (",
    f"    <Svg width={{height * ASPECT}} height={{height}} viewBox=\"{vb[0]:.1f} {vb[1]:.1f} {vb[2]:.1f} {vb[3]:.1f}\" accessibilityLabel=\"BlinkRest\">",
]
for d, color in paths:
    lines.append(f'      <Path fill="{color}" d="{d}" />')
lines += ["    </Svg>", "  );", "}", ""]
OUT.write_text("\n".join(lines))
print(f"wrote {OUT.relative_to(ROOT)} aspect={aspect:.3f}")
